-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aircraft
(
    aircraft_id integer NOT NULL,
    aircraft_model character varying(30) NOT NULL,
    capacity integer,
    PRIMARY KEY (aircraft_id)
);

CREATE TABLE IF NOT EXISTS public.flight
(
    flight_id integer NOT NULL,
    departure timestamp without time zone NOT NULL,
    arrival timestamp without time zone NOT NULL,
    aircraft_id integer NOT NULL,
    arrival_airport integer,
    departure_airport integer,
    crew_id integer,
    PRIMARY KEY (flight_id)
);

CREATE TABLE IF NOT EXISTS public.airport
(
    airport_id integer NOT NULL,
    city character varying(50) NOT NULL,
    country character varying(30) NOT NULL,
    iata_code character varying(10) NOT NULL,
    PRIMARY KEY (airport_id)
);

CREATE TABLE IF NOT EXISTS public.crew
(
    crew_id integer NOT NULL,
    pilot character varying(50) NOT NULL,
    copilot character varying(50) NOT NULL,
    cabin_crew_id integer NOT NULL,
    PRIMARY KEY (crew_id)
);

CREATE TABLE IF NOT EXISTS public.cabin_crew
(
    cabin_crew_id integer NOT NULL,
    crew_boss character varying(30) NOT NULL,
    crew_member1 character varying(30),
    crew_member2 character varying(30),
    crew_member3 character varying(30),
    PRIMARY KEY (cabin_crew_id)
);

CREATE TABLE IF NOT EXISTS public.passanger
(
    passanger_id integer NOT NULL,
    name character varying(30) NOT NULL,
    surnames character varying(40) NOT NULL,
    email character varying(100),
    phone_number integer,
    PRIMARY KEY (passanger_id)
);

CREATE TABLE IF NOT EXISTS public.booking
(
    book_id integer NOT NULL,
    flight_id integer NOT NULL,
    class_type integer NOT NULL,
    date timestamp without time zone,
    PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS public.passanger_booking
(
    passanger_passanger_id integer NOT NULL,
    booking_book_id integer NOT NULL
);

ALTER TABLE IF EXISTS public.flight
    ADD FOREIGN KEY (aircraft_id)
    REFERENCES public.aircraft (aircraft_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flight
    ADD FOREIGN KEY (arrival_airport)
    REFERENCES public.airport (airport_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flight
    ADD FOREIGN KEY (departure_airport)
    REFERENCES public.airport (airport_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flight
    ADD FOREIGN KEY (crew_id)
    REFERENCES public.crew (crew_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.crew
    ADD FOREIGN KEY (cabin_crew_id)
    REFERENCES public.cabin_crew (cabin_crew_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.booking
    ADD FOREIGN KEY (flight_id)
    REFERENCES public.flight (flight_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.passanger_booking
    ADD FOREIGN KEY (passanger_passanger_id)
    REFERENCES public.passanger (passanger_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.passanger_booking
    ADD FOREIGN KEY (booking_book_id)
    REFERENCES public.booking (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;